### ISSUE TITLE
Skeleton reording fails when len(mapping_data["bones"]) > len(old_bone_order)

### ISSUE THREAD

**Issue by Hanabi111** [ShiftyChesh/UnrealModSkeletonFixer#1]
Hi,

My rig has a different number of bones (not sure why; all I've done is import the model into blender then export without leaf bones). When I run builder I get the following error:

> bone replacement for models with different numbers of bones are not yet supported.
> Continue by truncating new bones array? y/n
> y
> Traceback (most recent call last):
>   File "R:\Modding\Palworld\UnrealModSkeletonFixer-main\ModBuilder.py", line 147, in <module>
>     build_mods(dir_folders, config)
>   File "R:\Modding\Palworld\UnrealModSkeletonFixer-main\ModBuilder.py", line 97, in build_mods
>     bone_realignment(mod_name, mod_files)
>   File "R:\Modding\Palworld\UnrealModSkeletonFixer-main\ModBuilder.py", line 71, in bone_realignment
>     new_bones = mapper.bone_order_from_mapping(mapping_data, bone_order, name_mappings)
>   File "R:\Modding\Palworld\UnrealModSkeletonFixer-main\pythonfiles\mapper.py", line 45, in bone_order_from_mapping
>     del (old_bone_order[-1]) # delete last index
> IndexError: list assignment index out of range

It seems to delete from the list continuously until it is empty. Currently just trying to import Flambelle's rig from Palworld->Blender->Unreal->Palworld with no edits. I have attached the mod files and the fbx I was using.

[mapping.zip](https://github.com/ShiftyChesh/UnrealModSkeletonFixer/files/14177184/mapping.zip)
[mod.zip](https://github.com/ShiftyChesh/UnrealModSkeletonFixer/files/14177186/mod.zip)
[SK_LavaGirl.zip](https://github.com/ShiftyChesh/UnrealModSkeletonFixer/files/14177193/SK_LavaGirl.zip)

**Comment by Hanabi111** [comment]
Update seems to have fixed it. Thanks for making this!
